global:
  scrape_interval: 15s
  evaluation_interval: 15s

scrape_configs:
  - job_name: 'prometheus'
    static_configs:
      - targets: ['localhost:9090']

  - job_name: 'airflow'
    static_configs:
      - targets: ['airflow_webserver:8080']
    metrics_path: '/admin/metrics'
    scrape_interval: 30s

  - job_name: 'backend'
    static_configs:
      - targets: ['backend:8000']
    metrics_path: '/metrics'
    scrape_interval: 30s

  - job_name: 'postgres'
    static_configs:
      - targets: ['postgres:5432']
    scrape_interval: 60s
    
# global:
#   scrape_interval: 15s

# scrape_configs:
#   - job_name: 'fastapi_app'
#     metrics_path: /metrics
#     static_configs:
#       - targets: ['backend:8000']  # or 'host.docker.internal:8000' for local dev