FROM grafana/grafana:9.5.2

# Change default port to 3001
ENV GF_SERVER_HTTP_PORT=3001

# Environment variables
ENV GF_SECURITY_ADMIN_PASSWORD=admin
ENV GF_USERS_ALLOW_SIGN_UP=false

# Copy Grafana configuration and dashboards
COPY ./infrastructure/monitoring/grafana/provisioning /etc/grafana/provisioning
COPY ./infrastructure/monitoring/grafana/dashboards /var/lib/grafana/dashboards

# Expose the custom Grafana port
EXPOSE 3001