global:
  scrape_interval: 15s

scrape_configs:
  - job_name: 'fastapi_app'
    metrics_path: /metrics
    static_configs:
      - targets: ['backend:8000']  # or 'host.docker.internal:8000' for local dev